@host = http://localhost:8080
@token = {{login.response.body.data.accessToken}}
@refresh_token = {{login.response.body.data.refreshToken}}
@email = aqaurius213@gmail.com
@password = 1231233231
###
# @name login
POST {{host}}/auth/login 

{
    "email" : "{{email}}",
    "password" : "{{password}}"
}
###
POST {{host}}/auth/register

{
    "email" : "{{email}}",
    "password" : "{{password}}"
}

###
POST {{host}}/auth/refresh

{
    "refresh_token" : "{{refresh_token}}"
}

###
GET {{host}}/users/me
Authorization: Bearer {{token}}

###
PUT {{host}}/users/me
Authorization: Bearer {{token}}

{
    "name" : "asdadsad"
}

###
POST {{host}}/posts
Authorization: Bearer {{token}}

{
    "title" : "Title",
    "content" : "Content"
}

###
GET {{host}}/posts/me
Authorization: Bearer {{token}}

###
POST {{host}}/posts/ce6d86c5-2164-471c-bf41-644b5e20893d/like
Authorization: Bearer {{token}}

###
POST {{host}}/posts/ce6d86c5-2164-471c-bf41-644b5e20893d/dislike
Authorization: Bearer {{token}}