@host = http://localhost:8080
@token = {{login.response.body.data.accessToken}}
@refresh_token = {{login.response.body.data.refreshToken}}
@email = aqaurius2@gmail.com
@password = 123123
###
# @name login
POST {{host}}/auth/login 

{
    "email" : "{{email}}",
    "password" : "{{password}}"
}
###
POST {{host}}/auth/register

{
    "email" : "{{email}}",
    "password" : "{{password}}"
}

###
POST {{host}}/auth/refresh

{
    "refresh_token" : "{{refresh_token}}"
}

###
GET {{host}}/users/me
Authorization: Bearer {{token}}

###
PUT {{host}}/users/me
Authorization: Bearer {{token}}

{
    "name" : "asdadsad"
}

###
POST {{host}}/posts
Authorization: Bearer {{token}}

{
    "title" : "Title",
    "content" : "Content"
}

###
GET {{host}}/posts/me
Authorization: Bearer {{token}}