@host = http://localhost:8080
@token = {{login.response.body.data.accessToken}}
@refresh_token = {{login.response.body.data.refreshToken}}
@email = aqaurius213@gmail.com
@password = 1231233231
###
# @name login
POST {{host}}/auth/login 

{
    "email" : "{{email}}",
    "password" : "{{password}}"
}
###
POST {{host}}/auth/register

{
    "email" : "{{email}}",
    "password" : "{{password}}"
}

###
POST {{host}}/auth/refresh

{
    "refresh_token" : "{{refresh_token}}"
}

###
GET {{host}}/users/me
Authorization: Bearer {{token}}
    
###
PUT {{host}}/users/me
Authorization: Bearer {{token}}

{
    "name" : "asdadsad"
}

###
POST {{host}}/posts
Authorization: Bearer {{token}}

{
    "title" : "Title",
    "content" : "Content"
}

###
GET {{host}}/posts/me?limit=3
Authorization: Bearer {{token}}

###
POST {{host}}/posts/2ef2163c-150f-43d9-bd73-a190b2a2be32/like
Authorization: Bearer {{token}}

###
POST {{host}}/posts/91468d3c-8eab-4a2b-ae2f-2f729e732b6f/dislike
Authorization: Bearer {{token}}

###
GET {{host}}/posts/reacts?postIds=91468d3c-8eab-4a2b-ae2f-2f729e732b6f&&postIds=2ef2163c-150f-43d9-bd73-a190b2a2be32
Authorization: Bearer {{token}}