version: '3.7'
networks:
  cleango:
    name: cleango
services:
  cleango:
    build:
      context: ../..
      target: dev
    labels:
      - log_enabled=true
      - service_name=cleango
    environment:
      - DEBUG=${DEBUG}
      - DEBUG_PORT=${DEBUG_PORT}
    env_file:
      - .env
    command:
      - air
    volumes:
      - ../..:/app
      - $HOME/go/pkg/mod:/go/pkg/mod
      - $HOME/.cache/go-build:/root/.cache/go-build
    ports:
      - ${DEBUG_PORT}:${DEBUG_PORT}
      - 8080:8080
    networks:
      - cleango
  # cassandra:
  #   image: bitnami/cassandra:latest
  #   ports: 
  #     - 9042:9042
  #   environment:
  #      - CASSANDRA_PASSWORD=cleango
  #      - CASSANDRA_USER=cleango
  #      - CASSANDRA_PASSWORD_SEEDER=yes
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: cleango
      POSTGRES_USER: cleango
      POSTGRES_DB: cleango
    ports:
      - 5432:5432
    networks:
      - cleango
  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=cleango
  #     - MONGO_INITDB_ROOT_PASSWORD=cleango
  #     - MONGO_INITDB_DATABASE=cleango
  #   networks:
  #     - cleango
  # eventstore:
  #   image: eventstore/eventstore:21.10.8-buster-slim
  #   ports:
  #     - 2113:2113
  #     - 1113:1113
  #   environment:
  #     - EVENTSTORE_CLUSTER_SIZE=1
  #     - EVENTSTORE_RUN_PROJECTIONS=All
  #     - EVENTSTORE_START_STANDARD_PROJECTIONS=true
  #     - EVENTSTORE_EXT_TCP_PORT=1113
  #     - EVENTSTORE_HTTP_PORT=2113
  #     - EVENTSTORE_INSECURE=true
  #     - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
  #     - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true