version: '3.7'
networks:
  kafka:
    name: kafka

services:
  nats:
    image: nats:alpine
    command: --jetstream
    ports:
      - 4222:4222
    networks:
      - kafka
  # kafka1:
  #   image: bitnami/kafka:latest
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9093
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
  #   networks:
  #     - kafka
  #   ports:
  #     - 9093:9093
  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   networks:
  #     - kafka
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
