scrape_configs:
  - job_name: win_node
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3002']
  - job_name: win_statsd
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9102']    
        labels: {'service': 'win'}
