// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/api/v1/api.proto

package apipb

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserEntity struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEntity) Reset()         { *m = UserEntity{} }
func (m *UserEntity) String() string { return proto.CompactTextString(m) }
func (*UserEntity) ProtoMessage()    {}
func (*UserEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b5225088fe8c43c, []int{0}
}
func (m *UserEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEntity.Unmarshal(m, b)
}
func (m *UserEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEntity.Marshal(b, m, deterministic)
}
func (m *UserEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEntity.Merge(m, src)
}
func (m *UserEntity) XXX_Size() int {
	return xxx_messageInfo_UserEntity.Size(m)
}
func (m *UserEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEntity.DiscardUnknown(m)
}

var xxx_messageInfo_UserEntity proto.InternalMessageInfo

func (m *UserEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetEntityRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" form:"id"`
	Offset               int      `protobuf:"varint,2,opt,name=offset,proto3,casttype=int" json:"offset,omitempty" form:"offset"`
	Limit                int      `protobuf:"varint,3,opt,name=limit,proto3,casttype=int" json:"limit,omitempty" form:"limit"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntityRequest) Reset()         { *m = GetEntityRequest{} }
func (m *GetEntityRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntityRequest) ProtoMessage()    {}
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b5225088fe8c43c, []int{1}
}
func (m *GetEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntityRequest.Unmarshal(m, b)
}
func (m *GetEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntityRequest.Marshal(b, m, deterministic)
}
func (m *GetEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntityRequest.Merge(m, src)
}
func (m *GetEntityRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntityRequest.Size(m)
}
func (m *GetEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntityRequest proto.InternalMessageInfo

func (m *GetEntityRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetEntityRequest) GetOffset() int {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetEntityRequest) GetLimit() int {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetEntityResponse struct {
	Entity               *types.Any   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Entities             []*types.Any `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetEntityResponse) Reset()         { *m = GetEntityResponse{} }
func (m *GetEntityResponse) String() string { return proto.CompactTextString(m) }
func (*GetEntityResponse) ProtoMessage()    {}
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b5225088fe8c43c, []int{2}
}
func (m *GetEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntityResponse.Unmarshal(m, b)
}
func (m *GetEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntityResponse.Marshal(b, m, deterministic)
}
func (m *GetEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntityResponse.Merge(m, src)
}
func (m *GetEntityResponse) XXX_Size() int {
	return xxx_messageInfo_GetEntityResponse.Size(m)
}
func (m *GetEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntityResponse proto.InternalMessageInfo

func (m *GetEntityResponse) GetEntity() *types.Any {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *GetEntityResponse) GetEntities() []*types.Any {
	if m != nil {
		return m.Entities
	}
	return nil
}

func init() {
	proto.RegisterType((*UserEntity)(nil), "proto.api.v1.UserEntity")
	proto.RegisterType((*GetEntityRequest)(nil), "proto.api.v1.GetEntityRequest")
	proto.RegisterType((*GetEntityResponse)(nil), "proto.api.v1.GetEntityResponse")
}

func init() { proto.RegisterFile("proto/api/v1/api.proto", fileDescriptor_4b5225088fe8c43c) }

var fileDescriptor_4b5225088fe8c43c = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xb1, 0xae, 0xd3, 0x30,
	0x18, 0x85, 0x49, 0x7a, 0x6f, 0x74, 0x6b, 0x2e, 0x08, 0xac, 0x02, 0x21, 0x43, 0x53, 0x65, 0xea,
	0x00, 0x76, 0x5b, 0x50, 0x10, 0x74, 0xa1, 0x91, 0x10, 0x1b, 0x43, 0x10, 0x0b, 0x62, 0x71, 0x1a,
	0x27, 0xb5, 0x48, 0xe2, 0x34, 0x76, 0x22, 0xf5, 0x99, 0x58, 0x78, 0x14, 0x9e, 0xa0, 0x0f, 0xc1,
	0xd8, 0xe9, 0x2a, 0x76, 0x9a, 0x56, 0x95, 0x3a, 0xf9, 0xd7, 0x39, 0xdf, 0xb1, 0x8f, 0x7e, 0x19,
	0xbc, 0x2c, 0x2b, 0x2e, 0x39, 0x26, 0x25, 0xc3, 0xcd, 0xbc, 0x3d, 0x90, 0x12, 0xe0, 0xbd, 0x3a,
	0x50, 0x2b, 0x34, 0x73, 0xe7, 0x75, 0xca, 0x79, 0x9a, 0x51, 0xac, 0xc4, 0xa8, 0x4e, 0x30, 0x29,
	0x76, 0x1a, 0x74, 0xdc, 0x4b, 0x4b, 0xb2, 0x9c, 0x0a, 0x49, 0xf2, 0xb2, 0x03, 0x5e, 0x74, 0x40,
	0xfb, 0xc4, 0x46, 0xca, 0xa3, 0xfc, 0xaa, 0x21, 0x19, 0x8b, 0x89, 0xa4, 0xf8, 0x38, 0x74, 0xc6,
	0x28, 0xe5, 0x29, 0xd7, 0xad, 0xda, 0x49, 0xab, 0xde, 0x0c, 0x80, 0x1f, 0x82, 0x56, 0x5f, 0x0a,
	0xc9, 0xe4, 0x0e, 0x3e, 0x05, 0x26, 0x8b, 0x6d, 0x63, 0x62, 0x4c, 0x87, 0xa1, 0xc9, 0x62, 0x08,
	0xc1, 0x4d, 0x41, 0x72, 0x6a, 0x9b, 0x4a, 0x51, 0xb3, 0xf7, 0xc7, 0x00, 0xcf, 0xbe, 0x52, 0xa9,
	0x13, 0x21, 0xdd, 0xd6, 0x54, 0x48, 0x38, 0x3d, 0x05, 0x03, 0xfb, 0x10, 0xdc, 0x55, 0xd6, 0x5f,
	0xc3, 0xf8, 0x67, 0x18, 0xff, 0xf7, 0xee, 0x30, 0xe1, 0x55, 0xfe, 0xc9, 0x63, 0xb1, 0xa7, 0xae,
	0xfc, 0x00, 0x2c, 0x9e, 0x24, 0x82, 0x4a, 0x75, 0xe9, 0x6d, 0xe0, 0x1e, 0x82, 0x1b, 0xc7, 0xfc,
	0xdc, 0x92, 0x4f, 0x34, 0xa9, 0x6d, 0xef, 0xb0, 0x77, 0x07, 0xac, 0x90, 0x61, 0x87, 0xc3, 0xf7,
	0xe0, 0x36, 0x63, 0x39, 0x93, 0xf6, 0x40, 0xe5, 0xc6, 0xa7, 0xdc, 0xbd, 0xce, 0x29, 0xb7, 0x8f,
	0x69, 0xd8, 0x13, 0xe0, 0xf9, 0x59, 0x59, 0x51, 0xf2, 0x42, 0x50, 0xf8, 0x06, 0x58, 0x54, 0x29,
	0xaa, 0xf1, 0xe3, 0xc5, 0x08, 0xe9, 0x5d, 0xa2, 0xe3, 0xb2, 0xd1, 0xaa, 0xd8, 0x85, 0x1d, 0x03,
	0x67, 0xe0, 0x4e, 0x4d, 0x8c, 0x0a, 0xdb, 0x9c, 0x0c, 0xae, 0xf2, 0x3d, 0xb5, 0xf8, 0x05, 0xc0,
	0xaa, 0x64, 0xdf, 0x69, 0xd5, 0xb0, 0x35, 0x85, 0xdf, 0xc0, 0xb0, 0xaf, 0x00, 0xc7, 0xe8, 0xfc,
	0x03, 0xa0, 0xcb, 0x45, 0x3a, 0xee, 0x55, 0x5f, 0x77, 0xf7, 0x1e, 0x05, 0xcb, 0x9f, 0x1f, 0x53,
	0x26, 0x37, 0x75, 0x84, 0xd6, 0x3c, 0xc7, 0x64, 0x4b, 0xea, 0x8a, 0xd5, 0xc2, 0xf7, 0x7d, 0x1f,
	0xaf, 0x33, 0x4a, 0x8a, 0xb7, 0x29, 0xc7, 0xe5, 0xef, 0x14, 0xf7, 0x3f, 0xb0, 0x8c, 0x70, 0x33,
	0x5f, 0xaa, 0x21, 0xb2, 0x94, 0xfa, 0xee, 0x21, 0x00, 0x00, 0xff, 0xff, 0x73, 0x94, 0x71, 0x32,
	0xa0, 0x02, 0x00, 0x00,
}
