// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1/api.proto

package apipb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetEntityRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntityRequest) Reset()         { *m = GetEntityRequest{} }
func (m *GetEntityRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntityRequest) ProtoMessage()    {}
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dfa6b8f70674874, []int{0}
}
func (m *GetEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntityRequest.Unmarshal(m, b)
}
func (m *GetEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntityRequest.Marshal(b, m, deterministic)
}
func (m *GetEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntityRequest.Merge(m, src)
}
func (m *GetEntityRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntityRequest.Size(m)
}
func (m *GetEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntityRequest proto.InternalMessageInfo

type GetEntityResponse struct {
	Entity               *types.Any `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetEntityResponse) Reset()         { *m = GetEntityResponse{} }
func (m *GetEntityResponse) String() string { return proto.CompactTextString(m) }
func (*GetEntityResponse) ProtoMessage()    {}
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dfa6b8f70674874, []int{1}
}
func (m *GetEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntityResponse.Unmarshal(m, b)
}
func (m *GetEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntityResponse.Marshal(b, m, deterministic)
}
func (m *GetEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntityResponse.Merge(m, src)
}
func (m *GetEntityResponse) XXX_Size() int {
	return xxx_messageInfo_GetEntityResponse.Size(m)
}
func (m *GetEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntityResponse proto.InternalMessageInfo

func (m *GetEntityResponse) GetEntity() *types.Any {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*GetEntityRequest)(nil), "api.v1.GetEntityRequest")
	proto.RegisterType((*GetEntityResponse)(nil), "api.v1.GetEntityResponse")
}

func init() { proto.RegisterFile("api/v1/api.proto", fileDescriptor_1dfa6b8f70674874) }

var fileDescriptor_1dfa6b8f70674874 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xdd, 0xa5, 0x60, 0xbc, 0xcc, 0xa0, 0xb0, 0xf5, 0xa2, 0xf4, 0xe4, 0x41, 0x13, 0xb6,
	0x61, 0x2f, 0x9e, 0x3a, 0x10, 0xaf, 0x32, 0x6f, 0xde, 0x92, 0xf2, 0xcc, 0x82, 0x6b, 0xf2, 0xd6,
	0xbc, 0x14, 0xfa, 0xdf, 0x4b, 0xdb, 0x28, 0x32, 0x76, 0x09, 0xe1, 0xf7, 0x7e, 0x7c, 0xdf, 0x7b,
	0x6c, 0xae, 0xd0, 0xca, 0x6e, 0x25, 0x15, 0x5a, 0x81, 0xad, 0x27, 0xcf, 0xb3, 0xe1, 0xdb, 0xad,
	0xf2, 0xa5, 0xf1, 0xde, 0x1c, 0x40, 0x8e, 0x54, 0xc7, 0x2f, 0xa9, 0x5c, 0x3f, 0x29, 0xf9, 0xdd,
	0xe9, 0x88, 0x6c, 0x03, 0x81, 0x54, 0x83, 0x49, 0xb8, 0x4d, 0xc2, 0x10, 0xbe, 0x27, 0x4a, 0xb8,
	0xe0, 0x6c, 0xfe, 0x06, 0xf4, 0xea, 0xc8, 0x52, 0xbf, 0x83, 0x63, 0x84, 0x40, 0x45, 0xc5, 0xae,
	0xff, 0xb1, 0x80, 0xde, 0x05, 0xe0, 0x8f, 0x2c, 0x83, 0x91, 0x2c, 0x66, 0xf7, 0xb3, 0x87, 0xab,
	0xf5, 0x8d, 0x98, 0x02, 0xc5, 0x6f, 0xa3, 0xa8, 0x5c, 0xbf, 0x4b, 0xce, 0xfa, 0x9d, 0xb1, 0x0a,
	0xed, 0x07, 0xb4, 0x9d, 0xad, 0x81, 0x6f, 0xd9, 0xe5, 0x5f, 0x20, 0x5f, 0x88, 0xe9, 0x1a, 0x71,
	0xda, 0x9b, 0x2f, 0xcf, 0x4c, 0xa6, 0xf6, 0xe2, 0x62, 0xfb, 0xfc, 0xb9, 0x31, 0x96, 0xf6, 0x51,
	0x8b, 0xda, 0x37, 0x52, 0x1d, 0x55, 0x6c, 0x6d, 0x0c, 0x65, 0x59, 0x96, 0xb2, 0x3e, 0x80, 0x72,
	0x4f, 0xc6, 0x4b, 0xfc, 0x36, 0x12, 0xf5, 0x70, 0x22, 0xea, 0x97, 0xf1, 0xd5, 0xd9, 0xb8, 0xde,
	0xe6, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xeb, 0xe8, 0xae, 0x55, 0x01, 0x00, 0x00,
}
