// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/apipb/v1/api.proto

package apipb

import (
	fmt "fmt"
	v1 "github.com/aqaurius6666/clean-go/pkg/proto/entitypb/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RegisterPostRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterPostRequest) Reset()         { *m = RegisterPostRequest{} }
func (m *RegisterPostRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterPostRequest) ProtoMessage()    {}
func (*RegisterPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{0}
}
func (m *RegisterPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterPostRequest.Unmarshal(m, b)
}
func (m *RegisterPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterPostRequest.Marshal(b, m, deterministic)
}
func (m *RegisterPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterPostRequest.Merge(m, src)
}
func (m *RegisterPostRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterPostRequest.Size(m)
}
func (m *RegisterPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterPostRequest proto.InternalMessageInfo

func (m *RegisterPostRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterPostRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterPostResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterPostResponse) Reset()         { *m = RegisterPostResponse{} }
func (m *RegisterPostResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterPostResponse) ProtoMessage()    {}
func (*RegisterPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{1}
}
func (m *RegisterPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterPostResponse.Unmarshal(m, b)
}
func (m *RegisterPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterPostResponse.Marshal(b, m, deterministic)
}
func (m *RegisterPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterPostResponse.Merge(m, src)
}
func (m *RegisterPostResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterPostResponse.Size(m)
}
func (m *RegisterPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterPostResponse proto.InternalMessageInfo

func (m *RegisterPostResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterPostResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type LoginPostRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginPostRequest) Reset()         { *m = LoginPostRequest{} }
func (m *LoginPostRequest) String() string { return proto.CompactTextString(m) }
func (*LoginPostRequest) ProtoMessage()    {}
func (*LoginPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{2}
}
func (m *LoginPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginPostRequest.Unmarshal(m, b)
}
func (m *LoginPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginPostRequest.Marshal(b, m, deterministic)
}
func (m *LoginPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginPostRequest.Merge(m, src)
}
func (m *LoginPostRequest) XXX_Size() int {
	return xxx_messageInfo_LoginPostRequest.Size(m)
}
func (m *LoginPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginPostRequest proto.InternalMessageInfo

func (m *LoginPostRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginPostRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginPostResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,4,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginPostResponse) Reset()         { *m = LoginPostResponse{} }
func (m *LoginPostResponse) String() string { return proto.CompactTextString(m) }
func (*LoginPostResponse) ProtoMessage()    {}
func (*LoginPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{3}
}
func (m *LoginPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginPostResponse.Unmarshal(m, b)
}
func (m *LoginPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginPostResponse.Marshal(b, m, deterministic)
}
func (m *LoginPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginPostResponse.Merge(m, src)
}
func (m *LoginPostResponse) XXX_Size() int {
	return xxx_messageInfo_LoginPostResponse.Size(m)
}
func (m *LoginPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginPostResponse proto.InternalMessageInfo

func (m *LoginPostResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LoginPostResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginPostResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginPostResponse) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type RefreshPostRequest struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshPostRequest) Reset()         { *m = RefreshPostRequest{} }
func (m *RefreshPostRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshPostRequest) ProtoMessage()    {}
func (*RefreshPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{4}
}
func (m *RefreshPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshPostRequest.Unmarshal(m, b)
}
func (m *RefreshPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshPostRequest.Marshal(b, m, deterministic)
}
func (m *RefreshPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshPostRequest.Merge(m, src)
}
func (m *RefreshPostRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshPostRequest.Size(m)
}
func (m *RefreshPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshPostRequest proto.InternalMessageInfo

func (m *RefreshPostRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshPostResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,3,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshPostResponse) Reset()         { *m = RefreshPostResponse{} }
func (m *RefreshPostResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshPostResponse) ProtoMessage()    {}
func (*RefreshPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{5}
}
func (m *RefreshPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshPostResponse.Unmarshal(m, b)
}
func (m *RefreshPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshPostResponse.Marshal(b, m, deterministic)
}
func (m *RefreshPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshPostResponse.Merge(m, src)
}
func (m *RefreshPostResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshPostResponse.Size(m)
}
func (m *RefreshPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshPostResponse proto.InternalMessageInfo

func (m *RefreshPostResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshPostResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *RefreshPostResponse) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type MeGetRequest struct {
	XId                  string   `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"-"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeGetRequest) Reset()         { *m = MeGetRequest{} }
func (m *MeGetRequest) String() string { return proto.CompactTextString(m) }
func (*MeGetRequest) ProtoMessage()    {}
func (*MeGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{6}
}
func (m *MeGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeGetRequest.Unmarshal(m, b)
}
func (m *MeGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeGetRequest.Marshal(b, m, deterministic)
}
func (m *MeGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeGetRequest.Merge(m, src)
}
func (m *MeGetRequest) XXX_Size() int {
	return xxx_messageInfo_MeGetRequest.Size(m)
}
func (m *MeGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MeGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MeGetRequest proto.InternalMessageInfo

func (m *MeGetRequest) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

type MeGetResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeGetResponse) Reset()         { *m = MeGetResponse{} }
func (m *MeGetResponse) String() string { return proto.CompactTextString(m) }
func (*MeGetResponse) ProtoMessage()    {}
func (*MeGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{7}
}
func (m *MeGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeGetResponse.Unmarshal(m, b)
}
func (m *MeGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeGetResponse.Marshal(b, m, deterministic)
}
func (m *MeGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeGetResponse.Merge(m, src)
}
func (m *MeGetResponse) XXX_Size() int {
	return xxx_messageInfo_MeGetResponse.Size(m)
}
func (m *MeGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MeGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MeGetResponse proto.InternalMessageInfo

func (m *MeGetResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MeGetResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MeGetResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MePutRequest struct {
	XId                  string   `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"-"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MePutRequest) Reset()         { *m = MePutRequest{} }
func (m *MePutRequest) String() string { return proto.CompactTextString(m) }
func (*MePutRequest) ProtoMessage()    {}
func (*MePutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{8}
}
func (m *MePutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MePutRequest.Unmarshal(m, b)
}
func (m *MePutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MePutRequest.Marshal(b, m, deterministic)
}
func (m *MePutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MePutRequest.Merge(m, src)
}
func (m *MePutRequest) XXX_Size() int {
	return xxx_messageInfo_MePutRequest.Size(m)
}
func (m *MePutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MePutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MePutRequest proto.InternalMessageInfo

func (m *MePutRequest) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *MePutRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MePutResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MePutResponse) Reset()         { *m = MePutResponse{} }
func (m *MePutResponse) String() string { return proto.CompactTextString(m) }
func (*MePutResponse) ProtoMessage()    {}
func (*MePutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{9}
}
func (m *MePutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MePutResponse.Unmarshal(m, b)
}
func (m *MePutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MePutResponse.Marshal(b, m, deterministic)
}
func (m *MePutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MePutResponse.Merge(m, src)
}
func (m *MePutResponse) XXX_Size() int {
	return xxx_messageInfo_MePutResponse.Size(m)
}
func (m *MePutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MePutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MePutResponse proto.InternalMessageInfo

func (m *MePutResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MePutResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MePutResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PostsPostRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XId                  string   `protobuf:"bytes,3,opt,name=_id,json=Id,proto3" json:"-"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostsPostRequest) Reset()         { *m = PostsPostRequest{} }
func (m *PostsPostRequest) String() string { return proto.CompactTextString(m) }
func (*PostsPostRequest) ProtoMessage()    {}
func (*PostsPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{10}
}
func (m *PostsPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsPostRequest.Unmarshal(m, b)
}
func (m *PostsPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsPostRequest.Marshal(b, m, deterministic)
}
func (m *PostsPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsPostRequest.Merge(m, src)
}
func (m *PostsPostRequest) XXX_Size() int {
	return xxx_messageInfo_PostsPostRequest.Size(m)
}
func (m *PostsPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostsPostRequest proto.InternalMessageInfo

func (m *PostsPostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostsPostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostsPostRequest) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

type PostsPostResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatorId            string   `protobuf:"bytes,4,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostsPostResponse) Reset()         { *m = PostsPostResponse{} }
func (m *PostsPostResponse) String() string { return proto.CompactTextString(m) }
func (*PostsPostResponse) ProtoMessage()    {}
func (*PostsPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{11}
}
func (m *PostsPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsPostResponse.Unmarshal(m, b)
}
func (m *PostsPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsPostResponse.Marshal(b, m, deterministic)
}
func (m *PostsPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsPostResponse.Merge(m, src)
}
func (m *PostsPostResponse) XXX_Size() int {
	return xxx_messageInfo_PostsPostResponse.Size(m)
}
func (m *PostsPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostsPostResponse proto.InternalMessageInfo

func (m *PostsPostResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PostsPostResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostsPostResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostsPostResponse) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

type PostsMeGetRequest struct {
	XId                  string         `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"-" form:"-"`
	Pagination           *v1.Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PostsMeGetRequest) Reset()         { *m = PostsMeGetRequest{} }
func (m *PostsMeGetRequest) String() string { return proto.CompactTextString(m) }
func (*PostsMeGetRequest) ProtoMessage()    {}
func (*PostsMeGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{12}
}
func (m *PostsMeGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsMeGetRequest.Unmarshal(m, b)
}
func (m *PostsMeGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsMeGetRequest.Marshal(b, m, deterministic)
}
func (m *PostsMeGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsMeGetRequest.Merge(m, src)
}
func (m *PostsMeGetRequest) XXX_Size() int {
	return xxx_messageInfo_PostsMeGetRequest.Size(m)
}
func (m *PostsMeGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsMeGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostsMeGetRequest proto.InternalMessageInfo

func (m *PostsMeGetRequest) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *PostsMeGetRequest) GetPagination() *v1.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type PostsMeGetResponse struct {
	Results              []*PostsMeGetResponse_Post `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Pagination           *v1.Pagination             `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PostsMeGetResponse) Reset()         { *m = PostsMeGetResponse{} }
func (m *PostsMeGetResponse) String() string { return proto.CompactTextString(m) }
func (*PostsMeGetResponse) ProtoMessage()    {}
func (*PostsMeGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{13}
}
func (m *PostsMeGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsMeGetResponse.Unmarshal(m, b)
}
func (m *PostsMeGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsMeGetResponse.Marshal(b, m, deterministic)
}
func (m *PostsMeGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsMeGetResponse.Merge(m, src)
}
func (m *PostsMeGetResponse) XXX_Size() int {
	return xxx_messageInfo_PostsMeGetResponse.Size(m)
}
func (m *PostsMeGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsMeGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostsMeGetResponse proto.InternalMessageInfo

func (m *PostsMeGetResponse) GetResults() []*PostsMeGetResponse_Post {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *PostsMeGetResponse) GetPagination() *v1.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type PostsMeGetResponse_Post struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatorId            string   `protobuf:"bytes,4,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostsMeGetResponse_Post) Reset()         { *m = PostsMeGetResponse_Post{} }
func (m *PostsMeGetResponse_Post) String() string { return proto.CompactTextString(m) }
func (*PostsMeGetResponse_Post) ProtoMessage()    {}
func (*PostsMeGetResponse_Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6e1e101e00c0d16, []int{13, 0}
}
func (m *PostsMeGetResponse_Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsMeGetResponse_Post.Unmarshal(m, b)
}
func (m *PostsMeGetResponse_Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsMeGetResponse_Post.Marshal(b, m, deterministic)
}
func (m *PostsMeGetResponse_Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsMeGetResponse_Post.Merge(m, src)
}
func (m *PostsMeGetResponse_Post) XXX_Size() int {
	return xxx_messageInfo_PostsMeGetResponse_Post.Size(m)
}
func (m *PostsMeGetResponse_Post) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsMeGetResponse_Post.DiscardUnknown(m)
}

var xxx_messageInfo_PostsMeGetResponse_Post proto.InternalMessageInfo

func (m *PostsMeGetResponse_Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PostsMeGetResponse_Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostsMeGetResponse_Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostsMeGetResponse_Post) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterPostRequest)(nil), "proto.apipb.v1.RegisterPostRequest")
	proto.RegisterType((*RegisterPostResponse)(nil), "proto.apipb.v1.RegisterPostResponse")
	proto.RegisterType((*LoginPostRequest)(nil), "proto.apipb.v1.LoginPostRequest")
	proto.RegisterType((*LoginPostResponse)(nil), "proto.apipb.v1.LoginPostResponse")
	proto.RegisterType((*RefreshPostRequest)(nil), "proto.apipb.v1.RefreshPostRequest")
	proto.RegisterType((*RefreshPostResponse)(nil), "proto.apipb.v1.RefreshPostResponse")
	proto.RegisterType((*MeGetRequest)(nil), "proto.apipb.v1.MeGetRequest")
	proto.RegisterType((*MeGetResponse)(nil), "proto.apipb.v1.MeGetResponse")
	proto.RegisterType((*MePutRequest)(nil), "proto.apipb.v1.MePutRequest")
	proto.RegisterType((*MePutResponse)(nil), "proto.apipb.v1.MePutResponse")
	proto.RegisterType((*PostsPostRequest)(nil), "proto.apipb.v1.PostsPostRequest")
	proto.RegisterType((*PostsPostResponse)(nil), "proto.apipb.v1.PostsPostResponse")
	proto.RegisterType((*PostsMeGetRequest)(nil), "proto.apipb.v1.PostsMeGetRequest")
	proto.RegisterType((*PostsMeGetResponse)(nil), "proto.apipb.v1.PostsMeGetResponse")
	proto.RegisterType((*PostsMeGetResponse_Post)(nil), "proto.apipb.v1.PostsMeGetResponse.Post")
}

func init() { proto.RegisterFile("proto/apipb/v1/api.proto", fileDescriptor_c6e1e101e00c0d16) }

var fileDescriptor_c6e1e101e00c0d16 = []byte{
	// 1049 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xd6, 0xfa, 0x47, 0x1c, 0xbf, 0x24, 0x95, 0x33, 0x0d, 0xad, 0x59, 0x25, 0xcd, 0x76, 0x52,
	0x95, 0x24, 0x95, 0x77, 0x1b, 0x23, 0x45, 0x6a, 0x4a, 0x04, 0x36, 0x20, 0x14, 0x09, 0x50, 0xb4,
	0x85, 0x4a, 0x84, 0x94, 0x30, 0xb1, 0xa7, 0x9b, 0x21, 0xf6, 0xce, 0x66, 0x77, 0xd6, 0x34, 0x95,
	0x90, 0x00, 0x55, 0x42, 0x5c, 0xc3, 0x85, 0xff, 0x8b, 0x03, 0xb7, 0x9e, 0x38, 0x71, 0x44, 0x9c,
	0x22, 0x0e, 0x68, 0x67, 0xc6, 0xf6, 0x7a, 0x9d, 0xc4, 0x82, 0xaa, 0x27, 0x4f, 0xde, 0xbc, 0x79,
	0xdf, 0xf7, 0xbd, 0x37, 0xfb, 0x4d, 0xa0, 0x1a, 0x84, 0x5c, 0x70, 0x87, 0x04, 0x2c, 0x38, 0x74,
	0x7a, 0x1b, 0xc9, 0xc2, 0x96, 0x21, 0x74, 0x4d, 0xfe, 0xd8, 0x72, 0xc7, 0xee, 0x6d, 0x98, 0x8b,
	0x1e, 0xe7, 0x5e, 0x87, 0x26, 0x19, 0x0e, 0xf1, 0x7d, 0x2e, 0x88, 0x60, 0xdc, 0x8f, 0x54, 0xb6,
	0x79, 0xb3, 0x47, 0x3a, 0xac, 0x4d, 0x04, 0x75, 0xfa, 0x0b, 0xbd, 0xb1, 0xe0, 0x71, 0x8f, 0x2b,
	0x90, 0x64, 0xa5, 0xa3, 0xb7, 0x54, 0x84, 0xfa, 0x82, 0x89, 0x53, 0x85, 0xac, 0xd6, 0x7a, 0x5f,
	0xfd, 0xb4, 0x6a, 0x1e, 0xf5, 0x6b, 0x3c, 0xa0, 0x3e, 0x09, 0x58, 0xaf, 0xee, 0xf0, 0x40, 0x42,
	0x8e, 0xc3, 0xe3, 0x2f, 0xe0, 0xba, 0x4b, 0x3d, 0x16, 0x09, 0x1a, 0xee, 0xf2, 0x48, 0xb8, 0xf4,
	0x24, 0xa6, 0x91, 0x40, 0x4b, 0x50, 0xa4, 0x5d, 0xc2, 0x3a, 0x55, 0xc3, 0x32, 0x56, 0xcb, 0xcd,
	0xd2, 0x79, 0xb3, 0x10, 0xe6, 0xbe, 0x36, 0x5c, 0x15, 0x45, 0x2b, 0x30, 0x1d, 0x90, 0x28, 0xfa,
	0x96, 0x87, 0xed, 0x6a, 0x3e, 0x95, 0x51, 0x99, 0x72, 0x07, 0x1b, 0xf8, 0x1d, 0x58, 0x18, 0x2d,
	0x1d, 0x05, 0xdc, 0x8f, 0x28, 0xba, 0x06, 0x39, 0xd6, 0x56, 0x85, 0xdd, 0x1c, 0x6b, 0xa3, 0x85,
	0x3e, 0x56, 0x4e, 0x86, 0xd4, 0x1f, 0xf8, 0x31, 0x54, 0x3e, 0xe6, 0x1e, 0xf3, 0xff, 0x27, 0xab,
	0xdc, 0x65, 0xac, 0x7e, 0x32, 0x60, 0x3e, 0x55, 0xf8, 0x12, 0x4e, 0x16, 0xcc, 0x90, 0x56, 0x8b,
	0x46, 0xd1, 0x67, 0xfc, 0x98, 0xfa, 0x9a, 0x59, 0x3a, 0x84, 0x30, 0xcc, 0x86, 0xf4, 0x69, 0x48,
	0xa3, 0x23, 0x95, 0x22, 0xdb, 0xe0, 0x8e, 0xc4, 0xd0, 0x22, 0x94, 0xe9, 0xb3, 0x80, 0x85, 0x34,
	0x6a, 0x88, 0x6a, 0xc1, 0x32, 0x56, 0xf3, 0xee, 0x30, 0x80, 0xbf, 0x03, 0xe4, 0xaa, 0xec, 0xb4,
	0x46, 0x0f, 0xe6, 0x74, 0x8d, 0x03, 0x21, 0x0b, 0x2b, 0xad, 0xcd, 0xf3, 0xe6, 0xbb, 0xe1, 0x76,
	0xfd, 0xe1, 0x57, 0xab, 0x5f, 0x92, 0xda, 0xf3, 0x46, 0x6d, 0xef, 0x7e, 0xed, 0xc1, 0xc1, 0xf6,
	0x93, 0x7b, 0x6b, 0xfb, 0xf6, 0xd5, 0x91, 0xfd, 0xda, 0xfe, 0xbd, 0x7d, 0x67, 0xfb, 0xc9, 0xfa,
	0xda, 0x28, 0x39, 0x7c, 0x9a, 0x4c, 0x3e, 0x05, 0xaf, 0x3b, 0x91, 0x51, 0x6e, 0x4c, 0x56, 0x9e,
	0x9b, 0xa4, 0x3c, 0x9f, 0x55, 0x7e, 0x17, 0x66, 0x3f, 0xa1, 0x1f, 0xd1, 0x81, 0xe6, 0x1b, 0x90,
	0x3f, 0xe8, 0xb7, 0xbf, 0x59, 0xfc, 0xf3, 0xe5, 0xb2, 0x51, 0x73, 0x73, 0x3b, 0x6d, 0xbc, 0x03,
	0x73, 0x3a, 0xef, 0xbf, 0x5c, 0x1d, 0x84, 0xa0, 0xe0, 0x93, 0x2e, 0xd5, 0x23, 0x91, 0x6b, 0xfc,
	0x61, 0x02, 0xb9, 0x1b, 0x4f, 0x82, 0x44, 0x4b, 0xfa, 0xac, 0xba, 0x3f, 0xe5, 0xf3, 0xe6, 0x54,
	0x58, 0xa8, 0xe4, 0xab, 0x75, 0x5d, 0x46, 0x32, 0x92, 0x65, 0x5e, 0x99, 0xd1, 0x09, 0x54, 0x92,
	0xc6, 0x47, 0xe9, 0xe1, 0x2f, 0x43, 0x51, 0x30, 0xd1, 0xa1, 0x9a, 0x57, 0x0a, 0x5e, 0xc5, 0xd1,
	0x1d, 0x28, 0xb5, 0xb8, 0x2f, 0xa8, 0x2f, 0x34, 0x43, 0x38, 0x6f, 0x96, 0xc2, 0x62, 0x25, 0x5f,
	0xfd, 0x3b, 0xef, 0xf6, 0xb7, 0xfa, 0xe2, 0xf2, 0xd9, 0x7e, 0x9e, 0xc0, 0x7c, 0x0a, 0xf2, 0x72,
	0x05, 0x8a, 0x83, 0x56, 0xa0, 0x80, 0xab, 0x43, 0x60, 0x25, 0x62, 0x00, 0xb6, 0x08, 0xe5, 0x56,
	0x48, 0x89, 0xe0, 0xe1, 0x4e, 0x5b, 0x5e, 0xf2, 0xb2, 0x3b, 0x0c, 0xe0, 0x9e, 0x86, 0x1c, 0x99,
	0x37, 0x4e, 0x37, 0x7f, 0x5e, 0xf2, 0xfb, 0xeb, 0xe5, 0xf2, 0xf4, 0x53, 0x1e, 0x76, 0xb7, 0x70,
	0x0d, 0xcb, 0x41, 0x6c, 0x03, 0x04, 0xc4, 0x63, 0xbe, 0x74, 0x2b, 0xc9, 0x65, 0xa6, 0xbe, 0xa4,
	0x4c, 0xcb, 0xee, 0xbb, 0x9f, 0xdd, 0xdb, 0xb0, 0x77, 0x07, 0x49, 0x6e, 0xea, 0x00, 0xfe, 0xc7,
	0x00, 0x94, 0x06, 0xd6, 0x62, 0x1b, 0x50, 0x0a, 0x69, 0x14, 0x77, 0x44, 0x54, 0x35, 0xac, 0xfc,
	0xea, 0x4c, 0xfd, 0x2d, 0x7b, 0xd4, 0xad, 0xed, 0xf1, 0x43, 0x32, 0xe4, 0xf6, 0xcf, 0xbd, 0x22,
	0x31, 0xb3, 0x0d, 0x85, 0xa4, 0xde, 0xeb, 0x6d, 0x7b, 0xfd, 0xe7, 0x12, 0x40, 0x23, 0x60, 0x8f,
	0x68, 0xd8, 0x63, 0x2d, 0x8a, 0x5e, 0x18, 0x30, 0x9b, 0xf6, 0x62, 0xb4, 0x92, 0x95, 0x7d, 0xc1,
	0x23, 0x60, 0xde, 0xb9, 0x3a, 0x49, 0x75, 0x07, 0xaf, 0x9d, 0x35, 0xa6, 0xa0, 0xd0, 0x88, 0xc5,
	0xd1, 0x8f, 0xbf, 0xfd, 0xf1, 0x4b, 0xce, 0xc4, 0x6f, 0xc8, 0x97, 0x2e, 0x79, 0x12, 0x63, 0x71,
	0xe4, 0x84, 0xfa, 0xcc, 0x96, 0xb1, 0x8e, 0x9e, 0x41, 0x79, 0x60, 0xbd, 0xc8, 0xca, 0x56, 0xcf,
	0xda, 0xbd, 0x79, 0xfb, 0x8a, 0x0c, 0x0d, 0x7e, 0x77, 0x14, 0xfc, 0x26, 0x46, 0x23, 0xe0, 0x9d,
	0xe4, 0x40, 0x82, 0xfc, 0xbd, 0x01, 0x33, 0x29, 0xb7, 0x43, 0x78, 0x5c, 0x5a, 0xd6, 0x89, 0xcd,
	0x95, 0x2b, 0x73, 0x34, 0x81, 0xd5, 0x51, 0x02, 0x6f, 0xe2, 0x85, 0x8c, 0x7a, 0x79, 0x24, 0xa1,
	0x10, 0x43, 0x51, 0x5e, 0x2b, 0xb4, 0x98, 0xad, 0x9b, 0xfe, 0x36, 0xcc, 0xa5, 0x4b, 0x76, 0x35,
	0x9e, 0x73, 0xd6, 0x58, 0x80, 0xe2, 0xe7, 0x11, 0x0d, 0xa3, 0xc3, 0x19, 0x28, 0x43, 0x89, 0x04,
	0xec, 0xe0, 0x98, 0x9e, 0x4a, 0x74, 0x84, 0x2a, 0x7d, 0xf4, 0x38, 0xc9, 0x70, 0xba, 0x54, 0xc1,
	0xee, 0xc6, 0x17, 0xc2, 0x0e, 0xfd, 0xf0, 0x22, 0xd8, 0x94, 0xcd, 0x4d, 0x80, 0x35, 0xc7, 0x61,
	0x7f, 0x30, 0xa0, 0x3c, 0xf0, 0x9a, 0xf1, 0x59, 0x67, 0x9d, 0x6f, 0x7c, 0xd6, 0x63, 0x46, 0xa5,
	0x39, 0xc8, 0xf8, 0x05, 0x1c, 0xf0, 0x5c, 0x9f, 0x43, 0x90, 0x64, 0x24, 0x1d, 0x7f, 0x61, 0x00,
	0x0c, 0x3f, 0x67, 0x74, 0xfb, 0xaa, 0x4f, 0x5d, 0xb1, 0xc0, 0x93, 0xdd, 0x60, 0x02, 0x8d, 0xe1,
	0x04, 0x24, 0x0d, 0xa7, 0x4b, 0x9b, 0xbf, 0x1b, 0x67, 0x8d, 0x5f, 0x0d, 0xf4, 0x01, 0xcc, 0xbe,
	0xdf, 0xa1, 0xc4, 0xaf, 0x79, 0xdc, 0x6a, 0xec, 0xee, 0x20, 0x78, 0x44, 0xba, 0x41, 0x87, 0x5a,
	0x24, 0x60, 0x78, 0x05, 0xca, 0x8f, 0x63, 0xeb, 0x53, 0x2f, 0x3e, 0xa5, 0xbe, 0x79, 0x83, 0x9c,
	0x90, 0x38, 0x64, 0x71, 0xb4, 0xb9, 0xb9, 0xb9, 0xf9, 0x9e, 0x97, 0x3c, 0x20, 0x76, 0x8b, 0x77,
	0xeb, 0xf9, 0x0d, 0xfb, 0x3e, 0x2e, 0xe9, 0xf2, 0xeb, 0x86, 0x51, 0xaf, 0x90, 0x20, 0xe8, 0xb0,
	0x96, 0xf4, 0x15, 0xe7, 0x9b, 0x88, 0xfb, 0x5b, 0x63, 0x91, 0x3d, 0x0b, 0x6e, 0x0d, 0x18, 0xa2,
	0xeb, 0xd3, 0x39, 0x73, 0x2e, 0xb9, 0xab, 0x3c, 0x64, 0xcf, 0x65, 0x92, 0x95, 0xdb, 0x7b, 0xe0,
	0x31, 0x71, 0x14, 0x1f, 0x26, 0x10, 0x4e, 0x1a, 0xd9, 0x69, 0x69, 0xb6, 0x4e, 0x70, 0xec, 0x39,
	0xa3, 0xff, 0xed, 0x3e, 0x94, 0x8b, 0xc3, 0x29, 0x19, 0x7d, 0xfb, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd1, 0x35, 0x04, 0x5b, 0x0c, 0x0b, 0x00, 0x00,
}
