// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// E is an autogenerated mock type for the E type
type E struct {
	mock.Mock
}

// IsEntity provides a mock function with given fields:
func (_m *E) IsEntity() {
	_m.Called()
}

type mockConstructorTestingTNewE interface {
	mock.TestingT
	Cleanup(func())
}

// NewE creates a new instance of E. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewE(t mockConstructorTestingTNewE) *E {
	mock := &E{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
