// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gentity "github.com/aqaurius6666/clean-go/pkg/gentity"
	mock "github.com/stretchr/testify/mock"
)

// Options is an autogenerated mock type for the Options type
type Options struct {
	mock.Mock
}

// apply provides a mock function with given fields: _a0
func (_m *Options) apply(_a0 *gentity.ExtendFields) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewOptions interface {
	mock.TestingT
	Cleanup(func())
}

// NewOptions creates a new instance of Options. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOptions(t mockConstructorTestingTNewOptions) *Options {
	mock := &Options{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
