// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/aqaurius6666/clean-go/internal/entities"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserUsecases is an autogenerated mock type for the UserUsecases type
type UserUsecases struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *UserUsecases) GetUser(ctx context.Context, id uuid.UUID) (*entities.User, error) {
	ret := _m.Called(ctx, id)

	var r0 *entities.User
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserUsecases interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserUsecases creates a new instance of UserUsecases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserUsecases(t mockConstructorTestingTNewUserUsecases) *UserUsecases {
	mock := &UserUsecases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
