// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/genericpb/generic.proto

package genericpb

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/gogoproto/types"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" form:"id"`
	Offset               int      `protobuf:"varint,2,opt,name=offset,proto3,casttype=int" json:"offset,omitempty" form:"offset"`
	Limit                int      `protobuf:"varint,3,opt,name=limit,proto3,casttype=int" json:"limit,omitempty" form:"limit"`
	OrderBy              string   `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty" form:"order_by"`
	IsAsc                bool     `protobuf:"varint,5,opt,name=is_asc,json=isAsc,proto3" json:"is_asc,omitempty" form:"is_asc"`
	Filters              string   `protobuf:"bytes,6,opt,name=filters,proto3" json:"filters,omitempty" form:"filters"`
	Joins                string   `protobuf:"bytes,7,opt,name=joins,proto3" json:"joins,omitempty" form:"joins"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03b6fd2178a80536, []int{0}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetRequest) GetOffset() int {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetRequest) GetLimit() int {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *GetRequest) GetIsAsc() bool {
	if m != nil {
		return m.IsAsc
	}
	return false
}

func (m *GetRequest) GetFilters() string {
	if m != nil {
		return m.Filters
	}
	return ""
}

func (m *GetRequest) GetJoins() string {
	if m != nil {
		return m.Joins
	}
	return ""
}

type GetResponse struct {
	Entity               *types.Any   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Entities             []*types.Any `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	Pagination           *Pagination  `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03b6fd2178a80536, []int{1}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetEntity() *types.Any {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *GetResponse) GetEntities() []*types.Any {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *GetResponse) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type Pagination struct {
	Offset               int      `protobuf:"varint,1,opt,name=offset,proto3,casttype=int" json:"offset"`
	Limit                int      `protobuf:"varint,2,opt,name=limit,proto3,casttype=int" json:"limit"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_03b6fd2178a80536, []int{2}
}
func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetOffset() int {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Pagination) GetLimit() int {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pagination) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PostRequest struct {
	Entity               *types.Any `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PostRequest) Reset()         { *m = PostRequest{} }
func (m *PostRequest) String() string { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()    {}
func (*PostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03b6fd2178a80536, []int{3}
}
func (m *PostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequest.Unmarshal(m, b)
}
func (m *PostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequest.Marshal(b, m, deterministic)
}
func (m *PostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequest.Merge(m, src)
}
func (m *PostRequest) XXX_Size() int {
	return xxx_messageInfo_PostRequest.Size(m)
}
func (m *PostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequest proto.InternalMessageInfo

func (m *PostRequest) GetEntity() *types.Any {
	if m != nil {
		return m.Entity
	}
	return nil
}

type PostResponse struct {
	Entity               *types.Any `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03b6fd2178a80536, []int{4}
}
func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetEntity() *types.Any {
	if m != nil {
		return m.Entity
	}
	return nil
}

type PutRequest struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Entity               *types.Any `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03b6fd2178a80536, []int{5}
}
func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutRequest) GetEntity() *types.Any {
	if m != nil {
		return m.Entity
	}
	return nil
}

type PutResponse struct {
	Entity               *types.Any `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03b6fd2178a80536, []int{6}
}
func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetEntity() *types.Any {
	if m != nil {
		return m.Entity
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03b6fd2178a80536, []int{7}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03b6fd2178a80536, []int{8}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "proto.genericpb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "proto.genericpb.GetResponse")
	proto.RegisterType((*Pagination)(nil), "proto.genericpb.Pagination")
	proto.RegisterType((*PostRequest)(nil), "proto.genericpb.PostRequest")
	proto.RegisterType((*PostResponse)(nil), "proto.genericpb.PostResponse")
	proto.RegisterType((*PutRequest)(nil), "proto.genericpb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "proto.genericpb.PutResponse")
	proto.RegisterType((*DeleteRequest)(nil), "proto.genericpb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "proto.genericpb.DeleteResponse")
}

func init() { proto.RegisterFile("proto/genericpb/generic.proto", fileDescriptor_03b6fd2178a80536) }

var fileDescriptor_03b6fd2178a80536 = []byte{
	// 660 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x4e, 0xdb, 0x4e,
	0x10, 0xc7, 0xb1, 0x8d, 0x4d, 0x98, 0xf0, 0x77, 0xc5, 0x4f, 0x3f, 0x37, 0x14, 0x1c, 0xed, 0x01,
	0xa5, 0x12, 0xb5, 0x2b, 0x5a, 0xa5, 0x52, 0xa9, 0x2a, 0x70, 0xa9, 0x90, 0xda, 0x4b, 0xe4, 0xaa,
	0x97, 0x5e, 0x90, 0x93, 0x6c, 0xcc, 0xb6, 0xc6, 0x6b, 0xec, 0x35, 0x52, 0x6e, 0x7d, 0x9e, 0x9e,
	0x78, 0x14, 0x5e, 0xa0, 0x79, 0x00, 0x8e, 0x1c, 0x73, 0xaa, 0xb2, 0xeb, 0x3f, 0x34, 0x24, 0x52,
	0xcb, 0xc9, 0xab, 0xf9, 0x7e, 0x66, 0x67, 0x32, 0xdf, 0xc9, 0xc2, 0x4e, 0x9c, 0x30, 0xce, 0x9c,
	0x80, 0x44, 0x24, 0xa1, 0xbd, 0xb8, 0x5b, 0x9c, 0x6c, 0x11, 0x47, 0xeb, 0xe2, 0x63, 0x97, 0x72,
	0xe3, 0x49, 0xc0, 0x58, 0x10, 0x12, 0x47, 0xc4, 0xbb, 0xd9, 0xc0, 0xf1, 0xa3, 0xa1, 0x64, 0x1b,
	0xff, 0xe5, 0x92, 0x1f, 0x53, 0xe7, 0x9c, 0xf3, 0x38, 0x0f, 0xff, 0x7f, 0xe5, 0x87, 0xb4, 0xef,
	0x73, 0xe2, 0x14, 0x87, 0x5c, 0xd8, 0x0a, 0x58, 0xc0, 0xf2, 0xf2, 0x2c, 0x60, 0x32, 0x8a, 0x7f,
	0xa9, 0x00, 0xa7, 0x84, 0x7b, 0xe4, 0x32, 0x23, 0x29, 0x47, 0x2d, 0x50, 0x69, 0xdf, 0x54, 0x9a,
	0x4a, 0x6b, 0xd9, 0x35, 0xc7, 0x6e, 0x2d, 0x31, 0x6e, 0x14, 0xe5, 0x5a, 0x51, 0xee, 0x46, 0xd6,
	0xf2, 0x80, 0x25, 0x17, 0x6f, 0x30, 0xed, 0x63, 0x4f, 0xa5, 0x7d, 0xf4, 0x1a, 0x0c, 0x36, 0x18,
	0xa4, 0x84, 0x9b, 0x6a, 0x53, 0x69, 0xe9, 0xae, 0x35, 0x76, 0x17, 0x1b, 0xea, 0xd1, 0x84, 0x5c,
	0x95, 0xa4, 0x94, 0xf1, 0x78, 0x64, 0x69, 0x34, 0xe2, 0x5e, 0x8e, 0xa3, 0x57, 0xa0, 0x87, 0xf4,
	0x82, 0x72, 0x53, 0x13, 0x79, 0xbb, 0x55, 0xde, 0x8a, 0xcc, 0x13, 0x6a, 0x99, 0x26, 0x61, 0xd4,
	0x86, 0x1a, 0x4b, 0xfa, 0x24, 0x39, 0xeb, 0x0e, 0xcd, 0x45, 0xd1, 0xde, 0xf6, 0xd8, 0xd5, 0x13,
	0xed, 0x46, 0xf4, 0xb6, 0x9e, 0x57, 0xcc, 0x09, 0xec, 0x2d, 0x89, 0xa3, 0x3b, 0x44, 0x2d, 0x30,
	0x68, 0x7a, 0xe6, 0xa7, 0x3d, 0x53, 0x6f, 0x2a, 0xad, 0x9a, 0xbb, 0x59, 0xf5, 0x27, 0xe3, 0xd8,
	0xd3, 0x69, 0x7a, 0x9c, 0xf6, 0xd0, 0x3e, 0x2c, 0x0d, 0x68, 0xc8, 0x49, 0x92, 0x9a, 0x86, 0x28,
	0x80, 0xee, 0x46, 0xd6, 0x9a, 0x44, 0x73, 0x01, 0x7b, 0x05, 0x82, 0xf6, 0x40, 0xff, 0xc6, 0x68,
	0x94, 0x9a, 0x4b, 0x82, 0xdd, 0xa8, 0xda, 0x17, 0x61, 0xec, 0x49, 0x19, 0xff, 0x54, 0xa0, 0x2e,
	0xe6, 0x9b, 0xc6, 0x2c, 0x4a, 0x09, 0xda, 0x07, 0x83, 0x44, 0x9c, 0xf2, 0xa1, 0x18, 0x72, 0xfd,
	0x60, 0xcb, 0x96, 0x36, 0xda, 0x85, 0xc3, 0xf6, 0x71, 0x34, 0xf4, 0x72, 0x06, 0xbd, 0x80, 0x9a,
	0x38, 0x51, 0x92, 0x9a, 0x6a, 0x53, 0x9b, 0xcb, 0x97, 0x14, 0x3a, 0x04, 0x88, 0xfd, 0x80, 0x46,
	0x3e, 0xa7, 0x2c, 0x12, 0x23, 0xae, 0x1f, 0x6c, 0xdb, 0x53, 0x6b, 0x65, 0x77, 0x4a, 0xc4, 0xbb,
	0x87, 0xe3, 0x1f, 0x0a, 0x40, 0x25, 0xa1, 0x67, 0xa5, 0xc5, 0x8a, 0xb0, 0x6a, 0xf3, 0x76, 0x64,
	0xe5, 0x91, 0x69, 0x53, 0xf7, 0x0a, 0x53, 0xe5, 0x32, 0x6c, 0xdc, 0x8e, 0x2c, 0x19, 0x98, 0xb2,
	0xd1, 0x02, 0x9d, 0x33, 0xee, 0x87, 0xa2, 0x33, 0xcd, 0x5d, 0x9e, 0x70, 0x22, 0xe0, 0xc9, 0x0f,
	0x3e, 0x84, 0x7a, 0x87, 0xa5, 0xe5, 0x3e, 0xfe, 0xd3, 0xb8, 0xf0, 0x5b, 0x58, 0x91, 0xc9, 0x8f,
	0x19, 0x36, 0xfe, 0x08, 0xd0, 0xc9, 0xca, 0xca, 0x6b, 0xd5, 0x3f, 0x41, 0xec, 0x7b, 0x75, 0x97,
	0xfa, 0x17, 0x77, 0x4d, 0x7e, 0x46, 0xf6, 0xd8, 0x46, 0x2c, 0x58, 0x3d, 0x21, 0x21, 0xe1, 0x64,
	0x4e, 0x2f, 0xb8, 0x09, 0x6b, 0x05, 0x90, 0x17, 0x98, 0x22, 0x0e, 0xae, 0x55, 0x40, 0xa7, 0xd2,
	0xee, 0xf7, 0xde, 0x97, 0x93, 0xcf, 0x24, 0xb9, 0xa2, 0x3d, 0x82, 0x5c, 0xd0, 0x4e, 0x09, 0x47,
	0x0f, 0x17, 0xa2, 0x7a, 0x02, 0x1a, 0x4f, 0x67, 0x8b, 0xb2, 0x10, 0x5e, 0x40, 0x1f, 0x60, 0x71,
	0x32, 0x64, 0xf4, 0x90, 0xbb, 0x67, 0x5c, 0x63, 0x67, 0x8e, 0x5a, 0x5e, 0xe3, 0x82, 0xd6, 0xc9,
	0x66, 0xb5, 0x52, 0x79, 0x30, 0xa3, 0x95, 0x7b, 0x43, 0xc5, 0x0b, 0xe8, 0x13, 0x18, 0x72, 0x0e,
	0x68, 0xf7, 0x01, 0xf9, 0xc7, 0x04, 0x1b, 0xd6, 0x5c, 0xbd, 0xb8, 0xcc, 0x3d, 0xfa, 0xfa, 0x2e,
	0xa0, 0xfc, 0x3c, 0xeb, 0xda, 0x3d, 0x76, 0xe1, 0xf8, 0x97, 0x7e, 0x96, 0xd0, 0x2c, 0x6d, 0xb7,
	0xdb, 0x6d, 0xa7, 0x17, 0x12, 0x3f, 0x7a, 0x1e, 0x30, 0x27, 0xfe, 0x1e, 0x38, 0x53, 0x2f, 0xf8,
	0x61, 0x79, 0xea, 0x1a, 0x42, 0x7a, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xae, 0x14, 0xd2,
	0xe5, 0x05, 0x00, 0x00,
}
